### ISSUE TITLE
Worked example?

### ISSUE THREAD

**Issue by sdwfrost** [TheoMichelot/MScrawl#1]
Hi @TheoMichelot 

Would it be possible to add in a worked example (e.g. using `simIOU` and `runMCMC`)?

**Comment by TheoMichelot** [comment]
Hi Simon,

Thanks for your interest, I just added a [script](https://github.com/TheoMichelot/MScrawl/blob/master/demo/MScrawl_sim.R) in the demo/ folder of the package. It simulates a track using simIOU, then thins it to irregular time intervals, and then uses runMCMC to recover the parameters.
I hope that this helps, please let me know if you have any questions about the package or the script.

Best wishes,
Théo
